//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsAppointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentCard
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int DoctorId { get; set; }
        public int PacientId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
